name: Build Frontend

on:
  push:
    paths: "Frontend/**"
  workflow_dispatch:

jobs:
  build:
    defaults:
      run:
        working-directory: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "22"
      - name: Clear npm configuration
        run: echo "" > ~/.npmrc
      - name: Set npm registry to public
        run: npm config set registry https://registry.npmjs.org/
      - name: Install Packages
        run: npm ci --force
      - name: Build
        run: ng build --base-href="/dhbwka-karteikarten/"
