name: CI – Frontend Build & Deploy

on:
  push:
    branches: [main, Doku]
  pull_request:
    branches: [main, Doku]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  # ---------------------
  # 1. FRONTEND (Lint, Test, Build)
  # ---------------------
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (Frontend)
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Use clean NPM registry config
        run: |
          rm -f ~/.npmrc
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc

      - name: Install frontend dependencies
        working-directory: Frontend
        run: npm ci --force

      - name: Build frontend
        working-directory: Frontend
        run: npm run build -- --base-href="/dhbwka-karteikarten/"

  # ---------------------
  # 2. DEPLOY FRONTEND TO GITHUB PAGES
  # ---------------------
  publish:
    needs: frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js for Pages build
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build frontend for Pages
        working-directory: Frontend
        run: |
          rm -f ~/.npmrc
          echo "registry=https://registry.npmjs.org/" > ~/.npmrc
          npm ci --force
          npm run build -- --base-href="/dhbwka-karteikarten/"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: "Frontend/dist/browser"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
